### PR TITLE
initial commit, recordset stack creation

### PR DESCRIPTION
**Pull request by fgimenez**
Initial commit + recordset stack creation. 

This tool aims to overcome the issue we have in China with disabled route53. Currently we need to manually create DNS recordsets on a european account that points to ELBs and instances in the China account. The tool will automate this process, both for creation and deletion of guest clusters.

It is meant to be executed as a circleci scheduled workload (kind of a cronjob). It retrieves main guest cluster stack names on the source AWS account (China), and checks on the target AWS account (Europe) if the recordsets for that guest cluster exist, creating them if not.

This PR includes general setup and recordset stack creation code.

### CODE REVIEW

**Comment by xh3b4sd** [comment]
Why the decision to run this as a scheduled job on Circle CI? Will Circle CI being broken result in our infrastructure not working anymore in China? Like is cluster creation then borked? What are the reasons and implications here?

**Comment by rossf7** [comment]
I think having automation for the recordset creation is good. Doing it manually is painful. Using Circle is not ideal but this is only needed until Route 53 becomes available in AWS China.

But I have a concern about the Etcd record set. It's a CNAME to the private DNS name of the master. This can change when the master is replaced. Will this be reconciled?

**Comment by fgimenez** [comment]
> Using Circle is not ideal but this is only needed until Route 53 becomes available in AWS China.

Indeed, also the tool is not bound to circleci by any means, we can run it elsewhere if needed.

> It's a CNAME to the private DNS name of the master. This can change when the master is replaced. Will this be reconciled?

Excellent catch! Not at all, we need to add code for doing so. Probably defining the etcd dns as an output would help to know the current state of the recordset, then try to update the stack if the actual value of the master instance private dns is different from it. I'll address this issue on a followup.

**Comment by fgimenez** [comment]
> When the record set creation does not screw the service quality of cluster creation, why do we even need it at all? Isn't it that without the record set any created cluster is unusable?

Yes, sadly this is the situation we have now in AWS China, because Route53 is not available there, after creating a guest cluster it is not directly usable. We need to manually create recordsets on a hosted zone created on a european account, that delegates to a domain accepted by Chinese procedures regarding DNS.

The goal of this project is making the experience as close to the rest of the regions as possible.

> Isn't there a concept in K8s which we can use? Something like scheduled jobs? See https://kubernetes.io/docs/tasks/job/automated-tasks-with-cron-jobs.

Absolutely, I think CronJob is the right concept to use here.

> Maybe chart operator could ensure these jobs somehow if the usual draughtsman magic does not fit.

IMO for the time being architect+draughtsman fit better this use case, we should have the CronJob running on the host cluster (and only on the chinese host cluster). 

I'll prepare a PR with the changes for making a CronJob from the tool in this repo, will ping you when ready.

**Comment by xh3b4sd** [comment]
I am still confused why we want to have a cronjob though? Why don't we have another operator just for this installation? What we do with a cronjob is to hack around the reconciliation and we have a pretty good concept for this, which is the operator. It should actually just watch for the provider CR and sort the record sets.

**Comment by fgimenez** [comment]
The problem I see with the operator is that it works well with k8s objects, the informers are suited to watch them and so on, but not so well with external ones. In this case, watching the CR is not enough, we would need to wait until the main guest stack is created to retrieve the DNS values for ingress ELB, API ELB and master instance, and then create the recordsets pointing to those values, and this info can only be retrieved from the provider, not from k8s API.

IMO having an operator that is not related to any CR, but to external info, doesn't align well with the operator concept, WDYT?

**Comment by kopiczko** [comment]
For me it also sounds like running an operator in circleci.
It's related to AWSConfigs CR. It can add its own finalizer. If you need to wait till some resources are ready resync period is your friend.

**Comment by xh3b4sd** [comment]
What Pawel said. I would strongly vote for having an operator. Watching the `AWSConfig` CR is just fine and it is the right thing because we have to support cluster creation. When the main stack is not yet there, skip the reconciliation and check in the next one again.

**Comment by rossf7** [comment]
My concern with building an operator is as soon as Route 53 is enabled in China we don't need this code any more.

Have we considered using `external-dns`? @r7vme is already using it for Azure and it has Route 53 support. 

https://github.com/kubernetes-incubator/external-dns

**Comment by puja108** [comment]
> My concern with building an operator is as soon as Route 53 is enabled in China we don't need this code any more.

Indeed, I would like to keep effort on this low, from our last info ETA for R53 in China is already August, so "worst" case we only use this for a few weeks, best case a few month.

**Comment by fgimenez** [comment]
Also, the current approach is already working, recordsets are already being automatically created. Missing code for updates and deletions.

**Comment by xh3b4sd** [comment]
Of course it is working already because you put the effort into it. IMO there is no difference in effort. Writing the operator boilerplate is done within 30 minutes. The difference is that the design is way more reliable IMO. I totally disagree with this approach here. I just hope you guys will not be proven wrong with your decisions taken here. I can see this easily failing. I said my thing now. Disagree and commit.

**Comment by kopiczko** [comment]
> My concern with building an operator is as soon as Route 53 is enabled in China we don't need this code any more.

If this is going to happen soon, I agree this is fine to do this patchwork.

**Pull request merged**
